/**
 * Error taxonomy. Every API error response carries { code, message, details? }.
 * `code` is stable and machine-readable; clients switch on it, never on message.
 */
export const ERROR_CODES = {
  // auth
  AUTH_INITDATA_INVALID: 'AUTH_INITDATA_INVALID',
  AUTH_INITDATA_EXPIRED: 'AUTH_INITDATA_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_FORBIDDEN_ROLE: 'AUTH_FORBIDDEN_ROLE',
  AUTH_ADMIN_NOT_ALLOWLISTED: 'AUTH_ADMIN_NOT_ALLOWLISTED',

  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  OPTIMISTIC_LOCK: 'OPTIMISTIC_LOCK',
  FEATURE_DISABLED: 'FEATURE_DISABLED',

  // catalog
  SERVICE_NOT_PUBLISHABLE: 'SERVICE_NOT_PUBLISHABLE',
  SERVICE_INACTIVE: 'SERVICE_INACTIVE',
  MODERATION_REQUIRED: 'MODERATION_REQUIRED',

  // orders / escrow
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_NOT_PAYABLE: 'ORDER_NOT_PAYABLE',
  ORDER_LIMIT_EXCEEDED: 'ORDER_LIMIT_EXCEEDED',
  ESCROW_INVALID_TRANSITION: 'ESCROW_INVALID_TRANSITION',
  ESCROW_INSUFFICIENT_HOLD: 'ESCROW_INSUFFICIENT_HOLD',

  // payments
  PAYMENT_PROVIDER_UNKNOWN: 'PAYMENT_PROVIDER_UNKNOWN',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 'PAYMENT_WEBHOOK_SIGNATURE_INVALID',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',

  // ledger / payouts
  LEDGER_UNBALANCED: 'LEDGER_UNBALANCED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  PAYOUT_INVALID_TRANSITION: 'PAYOUT_INVALID_TRANSITION',
  PAYOUT_BELOW_MINIMUM: 'PAYOUT_BELOW_MINIMUM',

  // disputes
  DISPUTE_ALREADY_OPEN: 'DISPUTE_ALREADY_OPEN',
  DISPUTE_INVALID_TRANSITION: 'DISPUTE_INVALID_TRANSITION',
  DISPUTE_WINDOW_CLOSED: 'DISPUTE_WINDOW_CLOSED',

  // files
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const HTTP_STATUS_BY_CODE: Partial<Record<ErrorCode, number>> = {
  AUTH_INITDATA_INVALID: 401,
  AUTH_INITDATA_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_SESSION_REVOKED: 401,
  AUTH_FORBIDDEN_ROLE: 403,
  AUTH_ADMIN_NOT_ALLOWLISTED: 403,
  FEATURE_DISABLED: 403,
  VALIDATION_FAILED: 422,
  FILE_TYPE_NOT_ALLOWED: 415,
  FILE_TOO_LARGE: 413,
  NOT_FOUND: 404,
  CONFLICT: 409,
  IDEMPOTENCY_KEY_REUSED: 409,
  OPTIMISTIC_LOCK: 409,
  RATE_LIMITED: 429,
  INTERNAL: 500,
};
